### DISCUSSION TITLE
Centralize storage of vocabulary tables / indices around source -> code deals with usage

### DISCUSSION THREAD

**Discussion by fenekku** [inveniosoftware/product-rdm#219] [Ideas]
## Motivation
InvenioRDM stores and indexes vocabularies locally. This reduces dependency on 3rd parties (are they up or down, slow or fast, correct or not) and give us/instance operators more control over the content.

The tradeoff is that the instance operators now need to store and index those vocabularies which can be huge (0.5M entries for LCSH, 19GB for LCNAF...) and in some cases, like ROR, the vocabulary has to be stored/indexed twice(multiple times) according to its function: organizations that are funders go in funders table/index and organizations that are affiliations go in affiliations table/index again. This latter point in particular is inefficient for instances with smaller available resources.    

## Proposal

Do like resource types, for at least organizations, and [rely on a tag](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/resource_types.yaml#L21) to identify the usage for each entry of such vocabulary. This way we limit storage duplicates.

Have a common organizations table/index and rely on tags to filter ones shown on different endpoints

```yaml
- acronym: CERN
  country: CH
  country_name: Switzerland
  id: 01ggx4157
  identifiers:
  - identifier: 01ggx4157
    scheme: ror
  - identifier: grid.9132.9
    scheme: grid
  - identifier: 0000 0001 2156 142X
    scheme: isni
  location_name: Geneva
  name: European Organization for Nuclear Research
  status: active
  title:
    de: Europäische Organisation für Kernforschung
    en: European Organization for Nuclear Research
    fr: Organisation européenne pour la recherche nucléaire
  types:
  - facility
  - funder
  tags:
    - affiliation
    - funder
```

This would save space and make management simpler in many cases.
